### ISSUE TITLE
Node 16.13 not compatible

### ISSUE THREAD

**Issue by joshuaVayer** [authdog/web-sdk#10]
## Expected Behavior
`yarn install` should finish with success

## Actual Behavior
Fail when using node 16.13

## Steps to Reproduce the Problem

  1. Use nvm to target 16.13 node version
  1. Run the command `yarn install`
  1. Check the terminal to see error

## Screenshots 

![image](https://github.com/authdog/web-sdk/assets/77019747/5ff5586e-db16-4a09-91a7-11921e2ccac5)

**Comment by dbrrt** [comment]
sounds like an issue related to `nx` which doesn't exist in this repo (maybe introduced as a dependency with the angular playground).
Can you clear your `node_modules` folder to see if the issue persists?
